spring.application.name=servico

spring.datasource.url=jdbc:postgresql://localhost:5432/db_produtos
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.dd-auto:validate

#RABBITMQ CONFIG
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

#RABBITMQ CUSTOM CONFIG
rabbitmq.exchange.name=produtos.v1.produto-criado
rabbitmq.queue.name=produtos.v1.produto-criado.fila
rabbitmq.routing-key=produto.criado