spring.application.name=pedidos

spring.datasource.url=jdbc:postgresql://localhost:5432/db_pedidos
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.dd-auto:validate

#RABBITMQ CONFIG
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

#RABBITMQ CUSTOM CONFIG
rabbitmq.exchange.name=exchange.v1.ecommerce-pedidos
rabbitmq.queue.name=queue.v1.ecommerce-pedido.fila.criado
rabbitmq.routing-key=pedido.criado

rabbitmq.queue.notificacao=queue.v1.ecommerce-pedido.fila.notificacao
rabbitmq.notificacao.routing-key=notificacao.enviada

server.port=8081

#CONFIGURANDO CIRCUIT BREAKER COM RESILIENCE4J
resilience4j.circuitbreaker.instances.adicionarPedido.failureRateThreshold: 50
resilience4j.circuitbreaker.instances.adicionarPedido.sliding-window-size: 5
resilience4j.circuitbreaker.instances.adicionarPedido.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.adicionarPedido.permitted-number-of-calls-in-half-open-state:3
