spring.application.name=notificacao

#RABBITMQ CONFIG
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

#RABBITMQ CUSTOM CONFIG
rabbitmq.exchange.name=exchange.v1.ecommerce-pedidos
rabbitmq.queue.name=queue.v1.ecommerce-pedido.fila.criado
rabbitmq.routing-key=pedido.criado

rabbitmq.queue.notificacao=queue.v1.ecommerce-pedido.fila.notificao
rabbitmq.notificacao.routing-key=notificacao.enviada

#SPRING MAIL
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.stmp.auth=false
spring.mail.properties.mail.stmp.starttls.enable=false
spring.mail.properties.mail.stmp.starttls.required=false	